### ISSUE TITLE
I take it this command is just to enter a container without going through the daemon?

### ISSUE THREAD

**Issue by rhatdan** [openshift/dockerexec#3]
Does it set the SELinux label correctly?  Does it drop to the corect Capabilities?  In the future do we want to setup the correct usernamespace and seccomp?

**Comment by ncdc** [comment]
Yes, this is to enter a container w/o going through the daemon. @mrunalp can you answer Dan's other questions?

**Comment by mrunalp** [comment]
@rhatdan This uses libcontainer code and so does the right thing w.r.t. capabilities and labels. As we vendor in newer versions, we will get newer features as well.

**Comment by rhatdan** [comment]
Awesome.  Is this something we should productise outside of openshift?  Calling it dockerexec might not be the best name...

**Comment by mrunalp** [comment]
Yeah, I agree that the name isn't very good. You can try pitching and see if it makes sense to productise it and have a better name :)

**Comment by rhatdan** [comment]
containerjoin
cjoin
transporter

**Comment by mrunalp** [comment]
ctrenter to add to the mix (similar to nsenter)
